services:
  nginx:
    image: nginx:1.31.1-alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php-fpm
    networks:
      - blog_net

  php-fpm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - blog_net

  mysql:
    image: mysql:8.4.9
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:root}
      MYSQL_DATABASE: ${DB_DATABASE:blog}
      MYSQL_USER: ${DB_USERNAME:blog_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:secrethuicret}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - blog_net

volumes:
  mysql_data:

networks:
  blog_net:
    driver: bridge